[package]
name = "crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.133", features = ["derive"] }
ed25519-dalek = { version = "1.0.1", features = ["batch", "serde"] }
base64 = "0.13.0"
bcs = "0.1.3"
serde-name = "0.2.0"
rand = "0.7.3"